version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase..........
      - echo This is temp-01 branch
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew installDist
      - zip -r build/sandbox-ktor.zip build/install/sandbox-ktor
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/sandbox-ktor.zip
